name: build and push image to github container registry

on:
  workflow_call:

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push-image:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
     - name: Checkout
       uses: actions/checkout@v4.1.1

     - name: Docker Login
       uses: docker/login-action@v3.0.0
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.ACTIONS_TOKEN }}

     - name: Setup Java JDK
       uses: actions/setup-java@v4.0.0
       with: 
         java-version: '17'
         distribution: 'temurin'
         
     - name: Gradle Build Action
       uses: gradle/gradle-build-action@v3.0.0
       with:
         gradle-version: '8.5'
       
     - name: Build and push Docker images
       uses: docker/build-push-action@v5.1.0
       with:
         context: .
         push: true
         tags: ghcr.io/${{ github.actor }}/bottle:1.0.2
  
