name: CI/CD Workflow

on:
  push:
    branches: [ "develop" ]
  
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: "build"
    uses: ./build-gradle.yml@main
    
