name: deploy image to Azure Kubernetes Service(AKS)

on:
  workflow_call:

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLUSTER_RESOURCE_GROUP: BottleResourceGroup
  CLUSTER_NAME: BottleManagedCluster
  CLUSTER_NAMESPACE: bottle
  IMAGE_TAG: 0.${{ github.RUN_NUMBER }}.0
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

            
       # add "--public-fqdn" if private cluster
      - name: Setting the target Azure Kubernetes Service (AKS) cluster.
        run: |
          az aks get-credentials \
            --resource-group ${{ env.CLUSTER_RESOURCE_GROUP }} \
            --name ${{ env.CLUSTER_NAME }} --overwrite-existing

      - name: Deploy using Helm
        run: |
          helm upgrade \
            --install ${{ github.event.repository.name }} helm-${{ github.event.repository.name }}/  \
            --set image.tag=${{ env.IMAGE_TAG }} --namespace ${{ env.CLUSTER_NAMESPACE }} --create-namespace \
            --wait

      - name: Verify Deployment
        run: kubectl rollout status deployment/${{ github.event.repository.name }} -n ${{ env.CLUSTER_NAMESPACE }}

        
